version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chatdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data